spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/api
    username: cjswo
    password: duddn
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: debug